name: Docker Hub
on:
  schedule:
    - cron: "20 4 * * 1"
  push:
    branches: 
      - main
    paths:
      - Dockerfile
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14", "16"]
    steps:
      - uses: actions/checkout@v3
      
      - uses: gautamkrishnar/keepalive-workflow@v1

      - run: sed -i "s/\$version/${{ matrix.node }}/g" Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: evenbit/firebase:node${{ matrix.node }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
